### ISSUE TITLE
Multistep conversions?

### ISSUE THREAD

**Issue by ArturGajowy** [tfausak/witch#52]
I'm toying with an idea where I'm trying to teach `witch` combine a couple steps for us, so e.g.:

```haskell
--syntax approximate, possibly a separate typeclass with different method name would be needed
-- functors
e1 = from @[Int] @[Int64] [1, 2]
-- containers via [] and Foldable - without depending on `vector`
e2 = from @(Vector Int) @(Set Int) $ V.fromList [1, 2]
-- containers and element conversion combined
e3 = from @(Vector Int) @(Set Int64) $ V.fromList [1, 2]
-- deep conversion
e4 = from @[Set String] @[[Text]] $ V.fromList [1, 2]
```

Granted, when attempted directly, this would cause massive overlap issues that - so far - I imagine one could attempt attacking by guiding typeclass resolution using a type family and another type parameter (probably in a different typeclass).

There's also usually not a unique path from A to B, but I imagine an API like
```haskell
f1 = magic @A @B
```
could pick an arbitrary path, and users could pick a specific path by combining `from` calls by hand.

What do you think of such direction?
Maybe you've gone down that path and can share why it's not worth pursuing?
Would multi-step conversions like above be a welcome addition?

**Comment by tfausak** [comment]
Setting aside containers for a second, consider this type:

``` hs
newtype Name = Name String
instance From String Name
```

If you want to convert a `Text` value into a `Name`, you have to do two conversions:

``` hs
let someText = pack "Artur"
in from @String @Name . from @Text @String $ someText
```

In these cases where you convert into some intermediate type, [the `via` function](https://hackage.haskell.org/package/witch-1.0.0.2/docs/Witch.html#v:via) can do those two steps for you:

``` hs
let someText = pack "Artur"
in via @String someText :: Name
```

This feels similar to your proposed `magic` function, except that there's not really any magic. Instead of writing `from @b @c . from @a @b`, you can write `via @b`. Unfortunately this only works if the path is unambiguous; there must be only one `From a b` instance and only one `From b c` instance. Also this falls apart if you introduce another type `d` into the mix; you end up with either `via @c . into @b` or `into @d . via @b`.

So that's what Witch has today that I feel is similar to what you're asking for. I'm happy to talk about adding more functionality, but my overall goal with Witch is to have it be unsurprising. By that I mean, if you see `from x`, you should be able to figure out what it's doing without really knowing anything about Witch. I feel like a `magic` function is very likely to run afoul of that.

**Comment by tfausak** [comment]
I think this is an interesting avenue to explore, but I don’t have the bandwidth to do so. I might accept a PT to add something like this to Witch, but I’d encourage you to build a proof of concept or separate package first.
