### ISSUE TITLE
Consider removing `ByteString` <-> `Text` instances?

### ISSUE THREAD

**Issue by mitchellwrosen** [tfausak/witch#56]
Hey, I couldn't find any discussion about this but apologies if it's a duplicate.

I'd like to propose removing the instances that convert between `Text` / `ByteString`. Rationalte: even though UTF-8 is ubiquitous, it's not canonical, and seems rather different than, say, casting an `Int16` to an `Int32` :)

**Comment by tfausak** [comment]
This comment mentions that the instance for converting from `Text` to `ByteString` arguably shouldn't exist: https://github.com/tfausak/witch/issues/17#issuecomment-829704290

And this pull request added a bunch of these instances, although they were mostly just wiring together existing instances: #34

I found a lot of other libraries that offer the same UTF-8 conversion between `Text` and `ByteString`:

- https://hackage.haskell.org/package/conversion-text-1.0.1.1/docs/Conversion-Text.html
- https://hackage.haskell.org/package/encode-string-0.1.0.0/docs/Data-String-Encode.html
- https://hackage.haskell.org/package/string-conv-0.2.0/docs/Data-String-Conv.html
- https://hackage.haskell.org/package/string-conversions-0.4.0.1/docs/Data-String-Conversions.html
- https://hackage.haskell.org/package/string-convert-4.0.0.1/docs/Text-StringConvert.html
- https://hackage.haskell.org/package/string-fromto-1.0.0.0/docs/Data-String-FromTo.html
- https://hackage.haskell.org/package/utf8-conversions-0.1.0.4/docs/Data-Convertible-Utf8.html

Not to say that they're right, of course 😄 

Anyway, I'm just providing all of that for context. I'm sympathetic to this argument. Converting from `Text` to `ByteString` makes about as much sense as converting from `Int32` to `Word32`. You certainly _can_ do the conversion, but you have to make a choice about how to you want to do it. For some reason I've decided that `From Text ByteString` is fine but `From Int32 Word32` is not. 

A big reason for me is simply ergonomics. If I've got `someFunction :: ByteString -> Int` and also `someText :: Text`, then it's super nice to simply say `someFunction (from someText)`. Now you might argue that just looking at it, it's not clear that you're going to end up with a UTF-8 encoded `ByteString`. That's fair. But it's also reasonable (I think) to assume that's what will happen. 

I feel like the right way out of this is to provide a wrapper type that picks the encoding. For example if you had `newtype Utf8 = Utf8 ByteString`, then you could say `via @Utf8 someText :: ByteString`. 

I haven't done that because it doesn't feel like Witch is the right library to provide such types. Also it would force me to decide which encodings to support, and it would balloon the number of instances. So instead I provide the "easy" choice of UTF-8, document it, and leave other conversions to other libraries. 

And as an aside, I think it's very unfortunate that both `encodeUtf8` and `encodeUtf16LE` have the same type signature: `Text -> ByteString`. Obviously the names of the functions disambiguate in that case. But for Witch there are no names, only types.

**Comment by mitchellwrosen** [comment]
I like that!

**Comment by tfausak** [comment]
These changes were released in version 1.1.0.0: https://hackage.haskell.org/package/witch-1.1.0.0
